[project]
name = "fxml"
version = "0.1.0"
description = "Cli tool for forex model training, backtesting, optimizing and data collecting using config files."
authors = [
    {name = "Dilshan Jayamanna",email = "dilshan.jayy@proton.me"}
]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "typer>=0.12.0",
    "rich>=13.7.0",
    "pandas>=2.2.0",
    "pandas-ta>=0.3.14b0",
    "sqlalchemy>=2.0.0",
    "alembic>=1.13.0",
    "psycopg2-binary>=2.9.0",
    "pydantic>=2.7.0",
    "pyyaml>=6.0.0",
    "python-dotenv>=1.0.0",
    "scikit-learn>=1.4.0",
    "requests>=2.31.0"
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "ruff>=0.3.0",
    "ipykernel (>=7.3.0,<8.0.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
fxml = "fxml.main:main"
